GET http://localhost:5000/api/v1/agencies/check?agency_id=BC_70001_077204005691
Content-Type: application/json

###

GET http://localhost:5000/api/v1/agencies/search
Content-Type: application/json

{
    "email": "buucucquan1@tdlogistics.com"
}

###

POST http://localhost:5000/api/v1/agencies/create
Content-Type: application/json

{
    "user_fullname": "Lữ Xuân Minh",
    "user_phone_number": "0981430417",
    "user_email": "minh.luxuanhcmut@hcmut.edu.vn",
    "user_date_of_birth": "2004-03-03",
    "user_cccd": "077204005691",
    "user_province": "Tỉnh Bà Rịa - Vũng Tàu",
    "user_district": "Huyện Đất Đỏ",
    "user_town": "Thị trấn Đất Đỏ",
    "user_detail_address": "326, ĐT44A",
    "user_position": "Quản lý bưu cục",
    "user_salary": 25000000,
    "type": "BC",
    "level": 3,
    "postal_code": "71000",
    "agency_name": "Bưu cục quận 1",
    "detail_address": "49, Phạm Ngũ Lão, phường Phạm Ngũ Lão, quận 1, Thành phố Hồ Chí Minh",
    "province": "Thành phố Hồ Chí Minh",
    "district": "Quận 1",
    "town": "Phường Phạm Ngũ Lão",
    "detail_address": "15, đường Phạm Ngũ Lão",
    "latitude": 10.7540931,
    "longitude": 106.0342813,
    "managed_wards": ["Phường Phạm Ngũ Lão", "Phường Đa Kao"],
    "phone_number": "0981430417",
    "email": "buucucquan1@gmail.com",
    "commission_rate": 0.4,
    "bin": "050138319579",
    "bank": "Sacombank",
    "individual_company": true,
    "company_name": "Công ty Cổ phần Bất động sản Tiến Dũng",
    "tax_number": "0123456789",
    "business_number": "01234"
}

###

PUT http://localhost:5000/api/v1/agencies/update?agency_id=BC_71000_077204005691
Content-Type: application/json

{
    "bin": "0981430418",
    "bank": "MB Bank"
}

###

PUT http://localhost:5000/api/v1/agencies//update_agency_company?agency_id=BC_71000_077204005691
Content-Type: application/json

{
    "company_name": "Công ty TNHH Viễn thông Tiến Dũng"
}

###

DELETE http://localhost:5000/api/v1/agencies/delete?agency_id=BC_71000_077204005691