POST http://localhost:5000/api/v1/staffs/login
content-type: application/json

{
    "cccd": "077204005692",
    "password": "123456"
}

###

POST http://localhost:5000/api/v1/staffs/create
content-type: application/json

{
    "fullname": "Lữ Xuân Minh",
    "username": "minhluxuan",
    "password": "qpk978",
    "date_of_birth": "2004-03-03",
    "cccd": "077204005692",
    "phone_number": "0981430418",
    "email": "minh.luxuanhcmut@hcmut.edu.vn",
    "role": "Giám đốc",
    "salary": 25000000,
    "paid_salary": 50000000,
    "address": "Thị trấn Đất Đỏ, Huyện Đất Đỏ, tỉnh Bà Rịa - Vũng Tàu",
    "agency_id": 72000
}

###

GET http://localhost:5000/api/v1/staffs/search?staff_id=000000001
content-type: application/json

###

GET http://localhost:5000/get_session
content-type: application/json

###

PATCH http://localhost:5000/api/v1/staffs/update?staff_id=000000001
content-type: application/json

{
    "role": "Nhân viên giao dịch",
    "paid_salary": 25000000
}

###

DELETE http://localhost:5000/api/v1/staffs/delete?staff_id=000000001
content-type: application/json