### "username": "buucucdatdo",
### "password": "Buucucquan1@tdlogistics"

POST http://localhost:5000/api/v1/orders/create
content-type: application/json

{
    "name_reciever": "NguyenVanB",
    "phone_reciever": "0787919943",
    "mass": 24,
    "height": 30,
    "width": 25,
    "length": 60,
    "province_source": "Tỉnh Bà Rịa - Vũng Tàu",
    "district_source": "Huyện Đất Đỏ",
    "ward_source": "Thị trấn Đất Đỏ",
    "detail_source": "Đường tỉnh 52, tổ 6 Khu phố Hiệp Hòa",
    "province_dest": "Tỉnh An Giang", 
    "district_dest": "Thành phố Long Xuyên",
    "ward_dest": "Phường Mỹ Long",
    "detail_dest": "20 Lý Thái Tổ",
    "long_source": 107.271563,
    "lat_source": 10.477812,
    "long_destination": 105.442062,
    "lat_destination": 10.377187,
    "COD": 32000,
    "service_type": 1
}

###

POST http://localhost:5000/api/v1/orders/calculatefee
Content-Type: application/json

{

    "address_source": "Đường tỉnh 52, tổ 6 Khu phố Hiệp Hòa, Thị trấn Đất Đỏ, Huyện Đất Đỏ, Tỉnh Bà Rịa - Vũng Tàu, Việt Nam",
    "address_dest": "20 Lý Thái Tổ, Phường Mỹ Long, Thành phố Long Xuyên, Tỉnh An Giang, Việt Nam"

}

###

GET http://localhost:5000/api/v1/orders/get_status
Content-Type: application/json

{
    "order_id" : "TD20241521249904"
}

###

GET http://localhost:5000/api/v1/orders/search_orderid
Content-Type: application/json

{
    "order_id" : "TD20241521249904"
}

###

GET http://localhost:5000/api/v1/orders/search_userid
Content-Type: application/json

{
    
}

###

GET http://localhost:5000/api/v1/orders/search_userid
Content-Type: application/json

{
    "status_code": 2
}

###

POST http://localhost:5000/api/v1/orders/create
content-type: application/json

{

    "name_sender": "Tran The Nhan",
    "phone_sender": "0787919942",
    "name_reciever": "Nguyen Van B",
    "phone_reciever": "0787919943",
    "mass": 24,
    "height": 30,
    "width": 25,
    "length": 60,
    "address_source": "Đường tỉnh 52, tổ 6 Khu phố Hiệp Hòa, Thị trấn Đất Đỏ, Huyện Đất Đỏ, Tỉnh Bà Rịa - Vũng Tàu, Việt Nam",
    "long_source": 107.271563,
    "lat_source": 10.477812,
    "address_dest": "979 Đường 2 Tháng 9, Phường 11, Thành phố Vũng Tàu, Tỉnh Bà Rịa - Vũng Tàu, Việt Nam",
    "long_destination": 107.134935,
    "lat_destination": 10.396995,
    "COD": 32000,
    "service_type": 3
}

###

GET http://localhost:5000/api/v1/orders/check?order_id=BC_78300_202422301010550
content-type: application/json

{
    
}