
POST http://localhost:5000/api/v1/shipment/create
Content-Type: application/json

{
    "staff_id": "HCM_NVT_001",
    "route": "TP.HCM-HANOI"
}

###

POST http://localhost:5000/api/v1/shipment/create
Content-Type: application/json

{
    "staff_id": "HCM_DVMH_001",
    "transport_partner_id": "TB001",
    "lat_source": 103.44532323,
    "long_source": 72.45353343,
    "lat_destination": 80.34342321,
    "long_destination": 34.553453453,
}

###

POST http://localhost:5000/api/v1/shipment/update
Content-Type: application/json

{
    "mass": 123,
    "shipment_id": "TD202405036131"
}

###

GET http://localhost:5000/api/v1/shipment/search
Content-Type: application/json

{
    "shipment_id": "TD202405036131"
}

###

POST http://localhost:5000/api/v1/shipment/decompose
Content-Type: application/json

{
    "shipment_id": "TD202405036131"
}

###

POST http://localhost:5000/api/v1/container/create
Content-Type: application/json

{
    "type" : "plane",
    "shipment_id": "TD202405188565",
    "container_id": "VNAIR3004"
}

###

POST http://localhost:5000/api/v1/container/update
Content-Type: application/json

{
    "choice" : "out",
    "shipment_id": "TD20240511925",
    "container_id": "50A-B1-56789"
}

###

POST http://localhost:5000/api/v1/container/update
Content-Type: application/json

{
    "choice" : "in",
    "shipment_id": "TD202405036131",
    "container_id": "50A-B1-56789"
}

###
GET http://localhost:5000/api/v1/container/search
Content-Type: application/json

{
    "container_id": "50A-B1-56789"
}

###

POST http://localhost:5000/api/v1/container/create
Content-Type: application/json

{
    "type" : "truck",
    "shipment_id": "TD202405188565",
    "container_id": "VNAIR3004"
}