POST http://localhost:5000/api/v1/otp/send_otp
content-type: application/json

{
    "phone_number": "0981430418",
    "email": "minh.luxuanhcmut@hcmut.edu.vn"
}

###

POST http://localhost:5000/api/v1/otp/verify_otp
content-type: application/json

{
    "phone_number": "0981430418",
    "email": "minh.luxuanhcmut@hcmut.edu.vn",
    "otp": 123456
}

###

GET http://localhost:5000/api/v1/users
content-type: application/json

###

GET http://localhost:5000/api/v1/users/search?email=minh.luxuancsk22@hcmut.edu.vn
content-type: application/json

###

POST http://localhost:5000/api/v1/users/check
content-type: application/json

{
    "phone_number": "0981430418"
}

###

POST http://localhost:5000/api/v1/users/create
content-type: application/json

{
    "email": "minh.luxuanhcmut@hcmut.edu.vn",
    "phone_number": "0981430418",
    "fullname": "Lữ Xuân Minh"
}

###

PATCH http://localhost:5000/api/v1/users/update
content-type: application/json

{
    "phone_number": "0981430418",
    "email": "minh.luxuancsk22@hcmut.edu.vn"
}


###

POST http://localhost:5000/api/v1/orders/create
content-type: application/json

{
    "order_id": "TD1254",
    "mass": 24,
    "height": 30,
    "width": 25,
    "length": 60,
    "long_source": 103.44,
    "lat_source": 72.4535,
    "long_destination": 80.343,
    "lat_destination": 34.55345
}

###

GET http://localhost:5000/get_session
content-type: application/json

###

GET http://localhost:5000/destroy_session
content-type: application/json

###

GET  http://localhost:3000/api/v1/vehicle/search?type=truck
content-type: application/json

###

POST  http://localhost:3000/api/v1/vehicle/search?type=truck
content-type: application/json

###

POST  http://localhost:3000/api/v1/vehicle/create
content-type: application/json
{
    "transport_partner_id": "TB003",
    "staff_id": "HCM_DVMH_002",
    "vehicle_id": "60B-C2-67890",
    "type": "van",
    "license_plate": "73B-678.90",
    "max_load": 1200
}

###

DELETE  http://localhost:3000/api/v1/vehicle/delete?vehicle_id=60B-C2-67890
content-type: application/json

###

PATCH  http://localhost:3000/api/v1/vehicle/update?vehicle_id=vehicle1
content-type: application/json
{
    "transport_partner_id": "TB003",
    "staff_id": "HCM_DVMH_002",
    "vehicle_id": "60B-C2-67890",
    "type": "van",
    "license_plate": "73B-678.90",
    "max_load": 1200,
    "order_id":{"append":["test1","test2"]}
}