GET http://localhost:5000/api/v1/drivers/get_objects
Content-Type: application/json

###

POST http://localhost:5000/api/v1/drivers/create_tasks
Content-Type: application/json

{
    "shipment_ids": ["BC_71000_202431213130926"],
    "vehicle_id": "TD_00001_42H124768"
}

###

POST http://localhost:5000/api/v1/drivers/get_tasks
Content-Type: application/json

{
    "staff_id": "BC_70001_077204005691",
    "option": 1
}

###

DELETE http://localhost:5000/api/v1/drivers/confirm_completed
Content-Type: application/json

{
    "id": 1
}