POST http://localhost:5000/api/v1/orders/search?rows=1&page=0
Content-Type: application/json

{

}

###

POST http://localhost:5000/api/v1/orders/rest_create
Content-Type: application/json

{
    "name_sender": "Lữ Xuân Minh",
    "name_receiver": "Trần Hữu Anh",
    "phone_number_receiver": "0981430418",
    "mass": 12,
    "height": 35,
    "width": 12,
    "length": 12,
    "province_source": "Thành phố Hồ Chí Minh",
    "district_source": "Quận 1",
    "ward_source": "Phường Đa Kao",
    "detail_source": "đường Võ Thị Sáu",
    "province_dest": "Tỉnh Bà Rịa - Vũng Tàu",
    "district_dest": "Thành phố Bà Rịa",
    "ward_dest": "Phường Phước Trung",
    "detail_dest": "đường Cách mạng tháng tám",
    "long_source": 10.38239932,
    "lat_source": 10.90237823,
    "long_destination": 10.3782238,
    "lat_destination": 10.38274242,
    "COD": 20000,
    "service_type": "CPN"
}

###

POST http://localhost:5000/api/v1/orders/search
Content-Type: application/json

{

}

###

PUT http://localhost:5000/api/v1/orders/update?order_id=BC_71000_202448162734963
Content-Type: application/json

{
    "mass": 29
}

###

DELETE http://localhost:5000/api/v1/orders/cancel?order_id=TD_00009_2024218234849782

###

POST https://api.tdlogistics.net.vn/api/v1/orders/calculate_fee
Content-Type: application/json

{
    "province_source": "Thành phố Hồ Chí Minh",
    "district_source": "Quận 1",
    "ward_source": "Phường Đa Kao",
    "detail_source": "Phố Đội Cấn",
    "province_dest": "Thành phố Hồ Chí Minh",
    "district_dest": "Quận 1",
    "ward_dest": "Phường Phạm Ngũ Lão",
    "detail_dest": "đường Phạm Ngũ Lão",
    "service_type": "CPN",
    "length": 30,
    "width": 20,
    "height": 10,
    "weight": 30000
}