POST http://localhost:5000/api/v1/orders/search?rows=1&page=0
Content-Type: application/json

{

}

###

POST https://tdlogistics.govt.hu/api/v1/orders/search
Content-Type: application/json

{

}

###

PUT http://localhost:5000/api/v1/orders/update?order_id=BC_71000_2024225161651124
Content-Type: application/json

{
    "mass": 30
}

###

DELETE http://localhost:5000/api/v1/orders/cancel?order_id=TD_00009_2024218234849782

###

POST http://localhost:5000/api/v1/orders/calculate_fee
Content-Type: application/json

{
    "province_source": "Hà Nội",
    "district_source": "Quận Ba Đình",
    "ward_source": "Phường Phúc Xá",
    "detail_source": "Phố Đội Cấn",
    "province_dest": "Thành phố Hồ Chí Minh",
    "district_dest": "Quận 1",
    "ward_dest": "Phường Phạm Ngũ Lão",
    "detail_dest": "đường Phạm Ngũ Lão",
    "service_type": "T60",
    "length": 12,
    "width": 4,
    "height": 10
}