GET  http://localhost:5000/api/v1/schedule/search
Content-Type: application/json

{
   "deadline": "2024-03-15 10:39:27",
   "priority": 4,
   "completed": false
}



###

POST http://localhost:5000/api/v1/schedule/create
Content-Type: application/json

{
   "deadline": "2024-03-15 10:39:27",
   "priority": 2,
   "task": "Create the universe 1"
}



 ###

PATCH http://localhost:5000/api/v1/schedule/update?id=1
Content-Type: application/json

{
   "deadline": "2024-03-15 10:39:27",
   "priority": 2,
   "task": "Undo the timer"
}

###

DELETE http://localhost:5000/api/v1/schedule/update?id=1