### tạo lô hàng cho đối tác vận tải trung chuyển
POST http://localhost:5000/api/v1/shipments/create
Content-Type: application/json

{
    "transport_partner_id": "TD_78300_077204005691"
}

### tạo lô hàng cho shipper giao hàng
POST http://localhost:5000/api/v1/shipments/create
Content-Type: application/json

{

}

### Trong cái cập nhật này mass có thể là số âm bởi vì mục tiêu của hàm này là cập nhật mass, append order_id (api khác của order)
### một cách thủ công khi không quét được lên lô hàng hay xuống lô hàng
POST http://localhost:5000/api/v1/shipments/update?shipment_id=BC_71000_202421221132823
Content-Type: application/json

{
   "mass": -134
}

### mass dương, lên hàng
POST http://localhost:5000/api/v1/shipments/update?shipment_id=BC_71000_202422224138948
Content-Type: application/json

{
    "mass": 200,
}
###  BC_78300_202429164715749
### order_id BC_78300_20242231694521, BC_78300_202422316114087, BC_78300_2024223161154877
### 39 40 41
POST http://localhost:5000/api/v1/shipments/add_orders?shipment_id=BC_78300_202429164715749
Content-Type: application/json

{
    "order_ids": ["BC_78300_20242231694521","BC_78300_202422316114087", "BC_78300_2024223161154877"]
}

###

POST http://localhost:5000/api/v1/shipments/remove_orders?shipment_id=BC_71000_202422224138948
Content-Type: application/json

{
    "order_ids": ["BC_78300_2024223163234692","BC_78300_2024223163234271", "BC_78300_2024223162829291"]
}

### TD2024132126392 TD2024132139335 TD2024132145338
POST http://localhost:5000/api/v1/shipments/remove_orders?shipment_id=BC_78300_202429164715749
Content-Type: application/json

{
    "order_ids": ["BC_78300_202422316114087", "BC_78300_2024223161154877"]
}

###
POST http://localhost:5000/api/v1/shipments/confirm_create
Content-Type: application/json 

{
    "shipment_id": "BC_78300_202421221351231"
}

### Chỉnh sửa database bảng 78300_shipment cột order_ids thêm 1 đơn hàng với 1 order_id đểu vào test chức năng xóa bưu cục 
POST http://localhost:5000/api/v1/shipments/confirm_create
Content-Type: application/json 

{
    "shipment_id": "BC_71000_202422224138948"
}

### Lấy thông tin lô hàng cho bưu cục 
POST http://localhost:5000/api/v1/shipments/search?rows=1&page=1
Content-Type: application/json

{
    
}

###

GET http://localhost:5000/api/v1/shipments/get_orders?shipment_id=BC_71000_202422224138948

###

DELETE http://localhost:5000/api/v1/shipments/delete?shipment_id=BC_71000_202422224138948
Content-Type: application/json 

###
POST http://localhost:5000/api/v1/shipments/updatedb
Content-Type: application/json 

{
    "shipment_id": "BC_71000_202421221132824"
}

###

GET http://localhost:5000/api/v1/shipments/get_orders?shipment_id=BC_78300_20242820443236
Content-Type: application/json

{
    
}


###

POST http://localhost:5000/api/v1/shipments/receive
Content-Type: application/json

{
    "shipment_id": "BC_71000_202422224138948"
}

###

POST http://localhost:5000/api/v1/shipments/decompose?shipment_id=BC_78300_202428204443125
Content-Type: application/json

{
    "order_ids": ["BC_78300_2024223163234692","BC_78300_2024223163234271","BC_78300_2024223162829291"]
}

###

POST http://localhost:5000/api/v1/shipments/undertake
Content-Type: application/json

{
    "shipment_id": "BC_71000_202422224138948",
    "status_code": 5
}

### api Test container 


###
POST http://localhost:5000/api/v1/containers/create
Content-Type: application/json

{
    "type" : "plane",
    "shipment_id": "TD20241211922797",
    "container_id": "VNAIR3004"
}

###

POST http://localhost:5000/api/v1/containers/update
Content-Type: application/json

{
    "choice" : "in",
    "shipment_id": "TD202412112533216",
    "container_id": "50A-B1-56789"
}

### Trường hợp quá tải trọng cho phép (SET 50A-B1-56789 đã có 399kg / 400kg)
### throw lỗi quá tải trọng 
POST http://localhost:5000/api/v1/containers/update
Content-Type: application/json

{
    "choice" : "in",
    "shipment_id": "TD202412112533216",
    "container_id": "50A-B1-56789"
}

###

POST http://localhost:5000/api/v1/containers/update
Content-Type: application/json

{
    "choice" : "out",
    "shipment_id": "TD202412112533216",
    "container_id": "50A-B1-56789"
}


###
GET http://localhost:5000/api/v1/containers/search
Content-Type: application/json

{
    "container_id": "50A-B1-56789"
}

###

POST http://localhost:5000/api/v1/container/create
Content-Type: application/json

{
    "type" : "truck",
    "shipment_id": "TD202405188565",
    "container_id": "VNAIR3004"
}

###
POST http://localhost:5000/api/v1/staffs/login
Content-Type: application/json

{
    "username": "buucucdatdo",
    "password": "Buucucquan1@tdlogistics"
}

###
POST http://localhost:5000/api/v1/shipments/undertake 
Content-Type: application/json

{
    "shipment_id": "BC_78300_202421221351231",
    "status_code": 3
}