
POST http://localhost:5000/api/v1/staffs/login
Content-Type: application/json

{
    "username": "minhluxuan2k15",
    "password": "minhluxuan@TDlogistics2k24"
}

###

PATCH http://localhost:5000/api/v1/staffs/update_password
Content-Type: application/json

{
    "new_password": "minhluxuan@TDlogistics2k24",
    "confirm_password": "minhluxuan@TDlogistics2k24"
}

###

POST http://localhost:5000/api/v1/shippers/create_tasks
Content-Type: application/json

{
    "shipment_id": "BC_71000_2024228225740952",
    "vehicle_id": "BC_71000_42H124768"
}

###

POST http://localhost:5000/api/v1/shippers/get_tasks
Content-Type: application/json

{
    "option": 0
}

###

PATCH http://localhost:5000/api/v1/shippers/confirm_completed?id=1
Content-Type: application/json

###

POST http://localhost:5000/api/v1/shippers/get_history
Content-Type: application/json

{
    "option": 3
}

###
POST http://localhost:5000/api/v1/orders/update_images?order_id=BC_78300_202422301019566&type=send
Content-Type: application/json

{
    
}