
POST http://localhost:5000/api/v1/staffs/login
Content-Type: application/json

{
    "username": "minhluxuan2k15",
    "password": "minhluxuan@TDlogistics2k24"
}

###

PATCH http://localhost:5000/api/v1/staffs/update_password
Content-Type: application/json

{
    "new_password": "minhluxuan@TDlogistics2k24",
    "confirm_password": "minhluxuan@TDlogistics2k24"
}

###

POST http://localhost:5000/api/v1/shippers/get_tasks
Content-Type: application/json

{
    "option": 1
}

###

PATCH http://localhost:5000/api/v1/shippers/confirm_completed
Content-Type: application/json

{
    "id": 14
}

###

POST http://localhost:5000/api/v1/shippers/get_history
Content-Type: application/json

{
    "option": 3
}
