POST http://localhost:5000/api/v1/staffs/login
Content-Type: application/json

{
    "username": "ntdung@tdlogistics",
    "password": "NTDung@tdlogistics2k24"
}

###

GET http://localhost:5000/api/v1/staffs/search
Content-Type: application/json

###

GET http://localhost:5000/api/v1/staffs/search
Content-Type: application/json

{
    "fullname": "Nguyễn Tiến Dũng"
}

###

POST http://localhost:5000/api/v1/staffs/create
Content-Type: application/json

{
    "agency_id": "TD_00000_077165007713",
    "username": "minhluxuan",
    "password": "minhluxuan@TDlogistics2k24",
    "fullname": "Lữ Xuân Minh",
    "phone_number": "0981430418",
    "email": "minh.luxuanhcmus@hcmut.edu.vn",
    "date_of_birth": "2004-03-03",
    "cccd": "077204005692",
    "province": "Tỉnh Bà Rịa - Vũng Tàu",
    "district": "Huyện Đất Đỏ",
    "town": "Thị trấn Đất Đỏ",
    "detail_address": "326, ĐT44A",
    "position": "Quản trị nhân sự",
    "role": "HUMAN_RESOURCE_MANAGER",
    "salary": 25000000
}

###

PUT http://localhost:5000/api/v1/staffs/update?staff_id=TD_00000_077204005692&agency_id=TD_00000_077165007713
Content-Type: application/json

{
    "email": "minh.luxuanhcmc@hcmut.edu.vn"
}

###

DELETE http://localhost:5000/api/v1/staffs/delete?staff_id=TD_00000_077204005692&agency_id=TD_00000_077165007713
Content-Type: application/json

###

PATCH http://localhost:5000/api/v1/staffs/update_password
Content-Type: application/json

{
    "new_password": "NTDung@tdlogistics2k24",
    "confirm_password": "NTDung@tdlogistics2k24"
}