
POST http://localhost:5000/api/v1/users/send_otp
Content-Type: application/json

{
    "phone_number": "0981430418",
    "email": "nhan.tranthek22cs@hcmut.edu.vn"
}

###

POST http://localhost:5000/api/v1/users/verify_otp
Content-Type: application/json

{
    "phone_number": "0981430418",
    "otp": 6790
}

###

GET http://localhost:5000/get_session