POST http://localhost:5000/api/v1/vehicles/search
Content-Type: application/json

{
    
}

###

POST http://localhost:5000/api/v1/vehicles/create
Content-Type: application/json

{
    
    "agency_id": "BC_70001_077204005691",
    "staff_id": "BC_70001_077204005684",
    "type": "motorbike",
    "license_plate": "72-H1 24768",
    "max_load": 50
}

###

POST http://localhost:5000/api/v1/vehicles/create
Content-Type: application/json

{
    "type": "motorbike",
    "agency_id": "BC_71000_077204005691",
    "staff_id": "BC_71000_077204005689",
    "license_plate": "42-H1 24768",
    "max_load": 50
}

###
POST http://localhost:5000/api/v1/vehicles/create
Content-Type: application/json

{
    
    "staff_id": "BC_70001_077204005684",
    "type": "motorbike",
    "license_plate": "72-H1 24768",
    "max_load": 50
}
###
POST http://localhost:5000/api/v1/vehicles/create
Content-Type: application/json

{
    
    "agency_id": "as",
    "staff_id": "BC_70001_077204005684",
    "type": "motorbike",
    "license_plate": "72-H1 24768",
    "max_load": 50
}
###
POST http://localhost:5000/api/v1/vehicles/create
Content-Type: application/json

{
    "agency_id": "BC_70001_077204005691",
    "staff_id": "invalid staff_id",
    "type": "motorbike",
    "license_plate": "72-H1 24768",
    "max_load": 50
}
###
POST http://localhost:5000/api/v1/vehicles/create
Content-Type: application/json

{
    
    "agency_id": "BC_70001_077204001691",
    "staff_id": "BC_70001_077204005684",
    "type": "motorbike",
    "license_plate": "72-H1 2768",
    "max_load": 50
}
###

PUT http://localhost:5000/api/v1/vehicles/update?vehicle_id=BC_70001_72H124767
Content-Type: application/json

{
    "max_load": 60
}
###
PUT http://localhost:5000/api/v1/vehicles/update?vehicle_id=BC_70001_72H124767
Content-Type: application/json

{
}
###

GET http://localhost:5000/api/v1/vehicles/search_order_ids?vehicle_id=BC_70001_72H124767

###

PATCH http://localhost:5000/api/v1/vehicles/add_orders?vehicle_id=BC_70001_72H124767
Content-Type: application/json

{
    "order_ids": ["TD202402225629673"]
}

###
PATCH http://localhost:5000/api/v1/vehicles/add_orders?vehicle_id=BC_70001_72H124767
Content-Type: application/json

{
    "order_ids": ["TD202452225629673","TD202402225629672"]
}
###

PATCH http://localhost:5000/api/v1/vehicles/delete_orders?vehicle_id=BC_70001_72H124767
Content-Type: application/json

{
    "order_ids": ["TD202402225629673"]
}

###

DELETE http://localhost:5000/api/v1/vehicles/delete?vehicle_id=BC_70001_72H124767
###
DELETE http://localhost:5000/api/v1/vehicles/delete?vehicle_id=invalid_vehicle_id

###
PATCH http://localhost:5000/api/v1/vehicles/delete_shipments?vehicle_id=BC_78300_67H112345
Content-Type: application/json

{
    "shipment_ids": ["TD202412112533216", "TD20240522616352", "TD20241211922797"]
}

###

PATCH http://localhost:5000/api/v1/vehicles/add_shipments?vehicle_id=BC_71000_42H124768
Content-Type: application/json

{
    "shipment_ids": ["BC_71000_202422224138948"]
}